const mockRepos = [
  {
    id: 326201918,
    node_id: "MDEwOlJlcG9zaXRvcnkzMjYyMDE5MTg=",
    name: "dearJournal",
    full_name: "romenick-tester/dearJournal",
    private: false,
    owner: {
      login: "romenick-tester",
      id: 75784246,
      node_id: "MDQ6VXNlcjc1Nzg0MjQ2",
      avatar_url: "https://avatars.githubusercontent.com/u/75784246?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/romenick-tester",
      html_url: "https://github.com/romenick-tester",
      followers_url: "https://api.github.com/users/romenick-tester/followers",
      following_url: "https://api.github.com/users/romenick-tester/following{/other_user}",
      gists_url: "https://api.github.com/users/romenick-tester/gists{/gist_id}",
      starred_url: "https://api.github.com/users/romenick-tester/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/romenick-tester/subscriptions",
      organizations_url: "https://api.github.com/users/romenick-tester/orgs",
      repos_url: "https://api.github.com/users/romenick-tester/repos",
      events_url: "https://api.github.com/users/romenick-tester/events{/privacy}",
      received_events_url: "https://api.github.com/users/romenick-tester/received_events",
      type: "User",
      site_admin: false
    }
  },
  {
    id: 320288421,
    node_id: "MDEwOlJlcG9zaXRvcnkzMjAyODg0MjE=",
    name: "devlink",
    full_name: "romenick-tester/devlink",
    private: false,
    owner: {
      login: "romenick-tester",
      id: 75784246,
      node_id: "MDQ6VXNlcjc1Nzg0MjQ2",
      avatar_url: "https://avatars.githubusercontent.com/u/75784246?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/romenick-tester",
      html_url: "https://github.com/romenick-tester",
      followers_url: "https://api.github.com/users/romenick-tester/followers",
      following_url: "https://api.github.com/users/romenick-tester/following{/other_user}",
      gists_url: "https://api.github.com/users/romenick-tester/gists{/gist_id}",
      starred_url: "https://api.github.com/users/romenick-tester/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/romenick-tester/subscriptions",
      organizations_url: "https://api.github.com/users/romenick-tester/orgs",
      repos_url: "https://api.github.com/users/romenick-tester/repos",
      events_url: "https://api.github.com/users/romenick-tester/events{/privacy}",
      received_events_url: "https://api.github.com/users/romenick-tester/received_events",
      type: "User",
      site_admin: false
    }
  },
  {
    id: 326252951,
    node_id: "MDEwOlJlcG9zaXRvcnkzMjYyNTI5NTE=",
    name: "kampiBasketball",
    full_name: "romenick-tester/kampiBasketball",
    private: false,
    owner: {
      login: "romenick-tester",
      id: 75784246,
      node_id: "MDQ6VXNlcjc1Nzg0MjQ2",
      avatar_url: "https://avatars.githubusercontent.com/u/75784246?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/romenick-tester",
      html_url: "https://github.com/romenick-tester",
      followers_url: "https://api.github.com/users/romenick-tester/followers",
      following_url: "https://api.github.com/users/romenick-tester/following{/other_user}",
      gists_url: "https://api.github.com/users/romenick-tester/gists{/gist_id}",
      starred_url: "https://api.github.com/users/romenick-tester/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/romenick-tester/subscriptions",
      organizations_url: "https://api.github.com/users/romenick-tester/orgs",
      repos_url: "https://api.github.com/users/romenick-tester/repos",
      events_url: "https://api.github.com/users/romenick-tester/events{/privacy}",
      received_events_url: "https://api.github.com/users/romenick-tester/received_events",
      type: "User",
      site_admin: false
    }
  },
  {
    id: 328733708,
    node_id: "MDEwOlJlcG9zaXRvcnkzMjg3MzM3MDg=",
    name: "proshop_2.0",
    full_name: "romenick-tester/proshop_2.0",
    private: false,
    owner: {
      login: "romenick-tester",
      id: 75784246,
      node_id: "MDQ6VXNlcjc1Nzg0MjQ2",
      avatar_url: "https://avatars.githubusercontent.com/u/75784246?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/romenick-tester",
      html_url: "https://github.com/romenick-tester",
      followers_url: "https://api.github.com/users/romenick-tester/followers",
      following_url: "https://api.github.com/users/romenick-tester/following{/other_user}",
      gists_url: "https://api.github.com/users/romenick-tester/gists{/gist_id}",
      starred_url: "https://api.github.com/users/romenick-tester/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/romenick-tester/subscriptions",
      organizations_url: "https://api.github.com/users/romenick-tester/orgs",
      repos_url: "https://api.github.com/users/romenick-tester/repos",
      events_url: "https://api.github.com/users/romenick-tester/events{/privacy}",
      received_events_url: "https://api.github.com/users/romenick-tester/received_events",
      type: "User",
      site_admin: false
    }
  }
]

export default mockRepos;