const mockUser = {
  login: "romenick-tester",
  id: 75784246,
  node_id: "MDQ6VXNlcjc1Nzg0MjQ2",
  avatar_url: "https://avatars.githubusercontent.com/u/75784246?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/romenick-tester",
  html_url: "https://github.com/romenick-tester",
  followers_url: "https://api.github.com/users/romenick-tester/followers",
  following_url: "https://api.github.com/users/romenick-tester/following{/other_user}",
  gists_url: "https://api.github.com/users/romenick-tester/gists{/gist_id}",
  starred_url: "https://api.github.com/users/romenick-tester/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/romenick-tester/subscriptions",
  organizations_url: "https://api.github.com/users/romenick-tester/orgs",
  repos_url: "https://api.github.com/users/romenick-tester/repos",
  events_url: "https://api.github.com/users/romenick-tester/events{/privacy}",
  received_events_url: "https://api.github.com/users/romenick-tester/received_events",
  type: "User",
  site_admin: false,
  name: "Romenick Tester",
  company: "Wicked Code!",
  blog: "www.romenicktester.com",
  location: "London, UK",
  email: null,
  hireable: null,
  bio: "Creator of Wicked Code!",
  twitter_username: "nick_tester",
  public_repos: 50,
  public_gists: 35,
  followers: 10495,
  following: 3,
  created_at: "2021-08-06T06:48:23Z",
  updated_at: "2021-07-08T05:01:32Z",
};

export default mockUser;